import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:url" content="https://www.kodasite.com/" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          property="og:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          property="og:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20Facebook%20updated.png?alt=media&token=d37ca8fa-c94f-4851-a70a-8c42411e603c"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="kodasite.com" />
        <meta property="twitter:url" content="https://www.kodasite.com/" />
        <meta
          name="twitter:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          name="twitter:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          name="twitter:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20updated.png?alt=media&token=f66bebb4-ae81-4e45-8ac6-ba7f46be2322"
        />
        <meta
          property="og:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          property="og:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          property="og:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20Facebook%20updated.png?alt=media&token=d37ca8fa-c94f-4851-a70a-8c42411e603c"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
