import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:image"
          content="https://next-og-generator.vercel.app/api/og?title=my post title"
        />
        {/* <meta property="og:url" content="https://www.kodasite.com/" />
        <meta property="og:type" content="website" />
        <meta
          property="og:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          property="og:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          property="og:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20Facebook%20updated.png?alt=media&token=d37ca8fa-c94f-4851-a70a-8c42411e603c"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="kodasite.com" />
        <meta property="twitter:url" content="https://www.kodasite.com/" />
        <meta
          name="twitter:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          name="twitter:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          name="twitter:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20updated.png?alt=media&token=f66bebb4-ae81-4e45-8ac6-ba7f46be2322"
        />
        <meta
          property="og:title"
          content="Koda | Join the Community of Experts."
        />
        <meta
          property="og:description"
          content="Get to know like-minded individuals, and share your expertise amongst each other."
        />
        <meta
          property="og:image"
          content="https://firebasestorage.googleapis.com/v0/b/koda-resources.appspot.com/o/OG%20Facebook%20updated.png?alt=media&token=d37ca8fa-c94f-4851-a70a-8c42411e603c"
        /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.og}>
          <div className={styles.ogTextContainer}>
            <h1 className={styles.header}>Koda.</h1>
            <p>
              Join a Community of business owners, techies, artists and aspiring
              enthusiasts who share their journeys and expertise.
            </p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
