import { GetServerSideProps, GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export const getServerSideProps: GetServerSideProps = async function ({
  query,
}) {
  const { title, description } = query;
  return {
    props: {
      title,
      description,
    },
  };
};

export default function posts({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta
          property="og:url"
          content="https://next-og-generator.vercel.app"
        />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={`${title} | ${description}.`} />

        <meta
          property="og:image"
          content={`https://next-og-generator.vercel.app/api/og?title=${title}&description=${description}`}
        />
      </Head>

      <main className={styles.main}>this is another apge</main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
